/* Intercollegiate Athletic Database Tables */
CREATE TABLE Customer (
    CustNo VARCHAR2(8) NOT NULL,
    CustName VARCHAR2(30) NOT NULL,
    Address VARCHAR2(50) NOT NULL,
    Internal CHAR(1) NOT NULL,
    Contact VARCHAR2(35) NOT NULL,
    Phone VARCHAR2(11) NOT NULL,
    City VARCHAR2(30) NOT NULL,
    State VARCHAR2(2) NOT NULL,
    Zip VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustNo)
);

CREATE TABLE Facility (
    FacNo VARCHAR2(8) NOT NULL,
    FacName VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_FACILITY PRIMARY KEY (FacNo),
    CONSTRAINT UNIQUE_FACNAME UNIQUE(FacName)
);

CREATE TABLE Location (
    LocNo VARCHAR2(8) NOT NULL,
    FacNo VARCHAR2(8) NOT NULL,
    LocName VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (LocNo),
    CONSTRAINT FK_FACILITY_LOCATION FOREIGN KEY (FacNo) REFERENCES FACILITY (FacNo)
);

CREATE TABLE EventRequest (
    EventNo VARCHAR2(8) NOT NULL,
    DateHeld DATE NOT NULL,
    DateReq DATE NOT NULL,
    CustNo VARCHAR2(8) NOT NULL,
    FacNo VARCHAR2(8) NOT NULL,
    DateAuth DATE,
    Status VARCHAR2(30) NOT NULL,
    EstCost NUMBER(38) NOT NULL,
    EstAudience NUMBER(38) NOT NULL,
    BudNo VARCHAR2(8),
    CONSTRAINT PK_EVENTREQUEST PRIMARY KEY (EventNo),
    CONSTRAINT FK_FACILITY_EVENTREQUEST FOREIGN KEY (FacNo) REFERENCES Facility (FacNo),
    CONSTRAINT FK_CUSTOMER_EVENTREQUEST FOREIGN KEY (CustNo) REFERENCES Customer (CustNo),
    CONSTRAINT CHECK_STATUS CHECK (Status IN ('Pending','Denied','Approved')),
    CONSTRAINT CHECK_AUDIENCE CHECK(EstAudience >0)
);

CREATE TABLE Employee (
    EmpNo VARCHAR2(8) NOT NULL,
    EmpName VARCHAR2(30) NOT NULL,
    Department VARCHAR2(30) NOT NULL,
    Email VARCHAR2(30) NOT NULL,
    Phone VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EmpNo)
);

CREATE TABLE ResourceTBL (
    ResNo VARCHAR2(8) NOT NULL,
    ResName VARCHAR2(30) NOT NULL,
    Rate NUMBER(38) NOT NULL,
    CONSTRAINT PK_RESOURCETBL PRIMARY KEY(ResNo),
    CONSTRAINT CHECK_RATE_POSITIVE CHECK (Rate > 0)
);

CREATE TABLE EventPlan (
    PlanNo VARCHAR2(8) NOT NULL,
    EventNo VARCHAR2(8) NOT NULL,
    WorkDate DATE NOT NULL,
    Notes VARCHAR2(30),
    Activity VARCHAR2(30) NOT NULL,
    EmpNo VARCHAR2(8),
    CONSTRAINT PK_EVENTPLAN PRIMARY KEY (PlanNo),
    CONSTRAINT FK_EVENTREQUEST_EVENTPLAN FOREIGN KEY (EventNo) REFERENCES EventRequest (EventNo),
    CONSTRAINT FK_EMPLOYEE_EVENTPLAN FOREIGN KEY (EmpNo) REFERENCES Employee (EmpNo)
);

CREATE TABLE EventPlanLine (
    PlanNo VARCHAR2(8) NOT NULL,
    LineNo VARCHAR2(8) NOT NULL,
    TimeStart DATE NOT NULL,
    TimeEnd DATE NOT NULL,
    NumberFLD NUMBER(38) NOT NULL,
    LocNo VARCHAR2(4) NOT NULL,
    ResNo VARCHAR2(4) NOT NULL,
    CONSTRAINT PK_EVENTPLANLINE PRIMARY KEY (PlanNo, LineNo),
    CONSTRAINT FK_EVENTPLAN_EVENTPLANLINE FOREIGN KEY (PlanNo) REFERENCES EventPlan (PlanNo),
    CONSTRAINT FK_LOCATION_EVENTPLANLINE FOREIGN KEY (LocNo) REFERENCES Location (LocNo),
    CONSTRAINT FK_RESOURCETBL_EVENTPLANLINE FOREIGN KEY (ResNo) REFERENCES ResourceTBL (ResNo),
    CONSTRAINT CHECK_TIME CHECK (TimeStart < TimeEnd)
);